#!/usr/bin/env bash

set -e

# Set variables
SYSTEM_TYPE=$(uname -s) # Get system type - Linux / macOS (Darwin)

set_up_dotbot () {
    CONFIG="install.conf.yaml"
    DOTBOT_DIR="dotbot"

    DOTBOT_BIN="bin/dotbot"
    BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    cd "${BASEDIR}"
    git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
    git submodule update --init --recursive "${DOTBOT_DIR}"

    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
}

install_homebrew_apps () {
    if [ "$SYSTEM_TYPE" = "Darwin" ]; then
        echo -e "Installing Homebrew applications:"

        # Installs packages in ~/.Brewfile, which was set up by Dotbot:
        brew bundle install --global
    fi
}

# Let's begin!
set_up_dotbot
install_homebrew_apps
# Fin