# Essentials
brew "git"
brew "tmux"

# Basics
brew "bat"
brew "micro"

# Monitoring and Performance
brew "speedtest-cli"

# CLI External Services
brew "asciinema"

# CLI Fun
brew "figlet"
brew "lolcat"
brew "neofetch"